// Enige bron van waarheid voor legacy (WordPress) URL-redirects.
// Gebruikt door:
//  - src/App.tsx        → client-side <Navigate> vangnet
//  - src/pages/NotFound.tsx → client-side vangnet
//  - vite.config.ts (redirectsPlugin) → public/_redirects (Netlify-formaat)
// Let op: dit bestand mag geen imports of aliassen gebruiken.

export interface LegacyRedirect {
  /** Pad zonder leading slash, zoals de oude WordPress-URL. */
  from: string;
  /** Nieuwe route, met leading slash. */
  to: string;
}

export const legacyRedirects: LegacyRedirect[] = [
  // Oude WordPress rubrieken
  { from: "belastingen", to: "/kennisbank" },
  { from: "ondernemen", to: "/kennisbank" },
  { from: "financien", to: "/kennisbank" },
  { from: "verzekeringen-info", to: "/kennisbank" },
  { from: "wet-en-regelgeving", to: "/kennisbank/wet-en-regelgeving" },
  { from: "movir", to: "/verzekeringen" },
  { from: "wijzijnaov", to: "/verzekeringen" },
  { from: "aov-via-centraalbeheer", to: "/verzekeringen" },
  { from: "sharepeople", to: "/partners" },
  { from: "eherkenning", to: "/kennisbank/eherkenning" },

  // Oude artikel-URL's
  { from: "verplichte-aov-voor-zzp", to: "/kennisbank/verplichte-aov-voor-zzp" },
  { from: "nieuwe-regels-zzp", to: "/kennisbank/nieuwe-regels-zzp-2025" },
  { from: "zelfstandigenwet-voor-zzp-ers", to: "/kennisbank/zelfstandigenwet-voor-zzp-ers" },
  {
    from: "vbar-wet-verduidelijking-beoordeling-arbeidsrelaties-en-rechtsvermoeden",
    to: "/kennisbank/vbar-wet-verduidelijking-arbeidsrelaties",
  },
  { from: "kleineondernemersregeling-kor", to: "/kennisbank/wijziging-kleineondernemersregeling-kor-2025" },
  { from: "wet-deregulering-beoordeling-arbeidsrelaties-dba", to: "/kennisbank/wet-dba-alles-wat-je-moet-weten" },
  { from: "hoeveel-opdrachtgevers-zzp", to: "/kennisbank/hoeveel-opdrachtgevers-zzp" },
  { from: "alles-over-een-zzp-factuur", to: "/kennisbank/alles-over-een-zzp-factuur" },
  { from: "inschrijven-bij-de-kamer-van-koophandel", to: "/kennisbank/inschrijven-bij-de-kamer-van-koophandel" },
  { from: "zzp-administratie-en-boekhouding", to: "/kennisbank/zzp-administratie-en-boekhouding" },
  { from: "hoe-bereken-ik-bijtelling-als-zzper", to: "/kennisbank/hoe-bereken-ik-bijtelling-als-zzper" },
  { from: "is-eten-en-drinken-aftrekbaar-als-zzp-er", to: "/kennisbank/is-eten-en-drinken-aftrekbaar-als-zzp-er" },
  { from: "hoe-zit-het-met-reiskosten-als-zzp-er", to: "/kennisbank/hoe-zit-het-met-reiskosten-als-zzp-er" },
  { from: "uurtarief-berekenen-zzper", to: "/kennisbank/uurtarief-berekenen-zzper" },
  {
    from: "hoeveel-kan-je-als-zzp-er-verdienen-zonder-belasting-te-moeten-betalen",
    to: "/kennisbank/hoeveel-kan-je-als-zzp-er-verdienen-zonder-belasting-te-moeten-betalen",
  },

  // Oude webshop-resten
  { from: "winkel", to: "/" },
  { from: "shop", to: "/" },
  { from: "product", to: "/" },
  { from: "mijn-account", to: "/" },
  { from: "my-account", to: "/" },

  // Bestaande zpzaken.nl URL's → nieuwe routes
  // Live WordPress-URL heeft een koppelteken tussen "bedrijfs" en
  // "aansprakelijkheidsverzekering"; beide varianten opgenomen.
  { from: "beroeps-en-bedrijfs-aansprakelijkheidsverzekering-zzp-avb-bav", to: "/verzekeringen" },
  { from: "beroeps-en-bedrijfsaansprakelijkheidsverzekering-zzp-avb-bav", to: "/verzekeringen" },
  // De bestemming beweegt automatisch mee met de publicatiestatus van het
  // artikel met dezelfde slug (zie resolveRedirectTarget). Zolang het artikel
  // op concept staat en niet zichtbaar is voor de anon-rol, geldt /zorgverzekering.
  { from: "bijdrage-zorgverzekeringswet-zzp", to: "/kennisbank/bijdrage-zorgverzekeringswet-zzp" },
  { from: "zzp-zorgverzekering", to: "/zorgverzekering" },
  { from: "mentale-gezondheidstest-mirro", to: "/mentale-gezondheid" },
  { from: "help-andere-zzpers", to: "/contact" },
  { from: "go/algemene-voorwaarden-zp", to: "/algemene-voorwaarden" },
  { from: "go/privacy-statement", to: "/cookies" },
  { from: "zpzakenaov-movir", to: "/aov" },
  { from: "arbeidsongeschiktheidsverzekering-aov-zzp", to: "/aov" },
  { from: "alles-over-verzekeringen-voor-zzpers", to: "/verzekeringen" },
  { from: "een-aov-bij-movir-aanvragen", to: "/aov" },
  { from: "contact-zpzaken", to: "/contact" },
  { from: "neem-gerust-contact-op", to: "/contact" },

  // Gangbare WordPress URL-patronen
  { from: "bav-verzekering", to: "/verzekeringen" },
  { from: "avb-verzekering", to: "/verzekeringen" },
  { from: "bav-avb", to: "/verzekeringen" },
  { from: "zzp-verzekering", to: "/verzekeringen" },
  { from: "zzp-verzekeringen", to: "/verzekeringen" },
  { from: "verzekering-zzp", to: "/verzekeringen" },
  { from: "aov-zzp", to: "/aov" },
  { from: "zzp-aov", to: "/aov" },
  { from: "pensioen-zzp", to: "/pensioen" },
  { from: "zzp-pensioen", to: "/pensioen" },
  { from: "zorgverzekering-zzp", to: "/zorgverzekering" },
  { from: "gratis-advies", to: "/contact" },
  { from: "adviesgesprek", to: "/contact" },
  { from: "aanvragen", to: "/verzekeringen" },
  { from: "afsluiten", to: "/verzekeringen" },
  { from: "blog", to: "/kennisbank" },
  { from: "nieuws", to: "/kennisbank" },
  { from: "artikel", to: "/kennisbank" },
  { from: "over", to: "/over-ons" },
  { from: "team", to: "/over-ons" },
  { from: "wie-zijn-wij", to: "/over-ons" },
  { from: "privacy", to: "/cookies" },
  { from: "privacyverklaring", to: "/cookies" },
   { from: "voorwaarden", to: "/documenten#verzekeringsvoorwaarden" },
   { from: "polisvoorwaarden", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "disclaimer", to: "/faq" },

  // Dubbele kennispagina: /kennis en /kennisbank deden hetzelfde
  { from: "kennis", to: "/kennisbank" },
  // --- Ronde 2: rankende WordPress-URL's die nog geen redirect hadden ---
  // Voor deze slugs bestaat een kennisbankartikel. De bestemming wordt bij de
  // build bepaald door resolveRedirectTarget(): gepubliceerd → /kennisbank/<slug>,
  // concept → categoriepagina. De waarde hieronder is de handmatige terugval.
  { from: "auto-van-de-zaak-of-prive", to: "/kennisbank/auto-van-de-zaak-of-prive" },
  { from: "zzp-of-eenmanszaak", to: "/kennisbank/zzp-of-eenmanszaak" },
  { from: "zzp-aftrekposten", to: "/kennisbank/zzp-aftrekposten" },
  { from: "zzp-er-met-een-bv-wat-zijn-de-voor-en-nadelen", to: "/kennisbank/zzp-er-met-een-bv-wat-zijn-de-voor-en-nadelen" },
  { from: "wet-toekomst-pensioenen-wtp-voor-zzp-ers", to: "/kennisbank/wet-toekomst-pensioenen-wtp-voor-zzp-ers" },
  { from: "welke-verzekeringen-zzp", to: "/kennisbank/welke-verzekeringen-zzp" },
  { from: "wat-kosten-verzekeringen-voor-zzp-ers", to: "/kennisbank/wat-kosten-verzekeringen-voor-zzp-ers" },
  { from: "rijd-je-als-zzp-er-fiscaal-voordelig-met-een-youngtimer", to: "/kennisbank/rijd-je-als-zzp-er-fiscaal-voordelig-met-een-youngtimer" },
  { from: "voordelen-van-zzp", to: "/kennisbank/voordelen-van-zzp" },
  { from: "hoe-combineer-je-loondienst-en-zzp", to: "/kennisbank/hoe-combineer-je-loondienst-en-zzp" },
  { from: "hoe-bereken-ik-mijn-inkomen-als-zzp-er-naast-loondienst", to: "/kennisbank/hoe-bereken-ik-mijn-inkomen-als-zzp-er-naast-loondienst" },
  { from: "wat-is-de-zelfstandigenaftrek", to: "/kennisbank/wat-is-de-zelfstandigenaftrek" },
  { from: "cyberverzekering-zzp", to: "/kennisbank/cyberverzekering-zzp" },
  { from: "zzp-en-belasting", to: "/kennisbank/zzp-en-belasting" },
  { from: "starten-met-ondernemen-als-zzper", to: "/kennisbank/starten-met-ondernemen-als-zzper" },
  { from: "wanneer-zelfstandig-ondernemer-voor-de-belastingdienst", to: "/kennisbank/wanneer-zelfstandig-ondernemer-voor-de-belastingdienst" },
  { from: "ondernemingsplan", to: "/kennisbank/ondernemingsplan" },
  { from: "wat-is-startersaftrek", to: "/kennisbank/wat-is-startersaftrek" },
  { from: "wat-is-het-urencriterium", to: "/kennisbank/wat-is-het-urencriterium" },
  { from: "voor-en-nadelen-broodfonds-of-schenkkring", to: "/kennisbank/voor-en-nadelen-broodfonds-of-schenkkring" },
  { from: "kleinschaligheidsinvesteringsaftrek-kia-voor-zzpers", to: "/kennisbank/kleinschaligheidsinvesteringsaftrek-kia-voor-zzpers" },
  { from: "schijnzelfstandigheid-als-zzp-er", to: "/kennisbank/schijnzelfstandigheid-als-zzp-er" },
  { from: "btw-aangifte-zzp", to: "/kennisbank/btw-aangifte-zzp" },
  { from: "hypotheek-berekenen-en-afsluiten-als-zzp-er", to: "/kennisbank/hypotheek-berekenen-en-afsluiten-als-zzp-er" },

  // Oude URL's zonder kennisbankartikel: vaste bestemming.
  { from: "moneysure-aov-alternatief", to: "/aov" },
  { from: "brightpensioen", to: "/pensioen" },
  // Geen /reviews-route in de app, daarom /contact.
  { from: "hoe-was-jouw-ervaring-met-zp-zaken", to: "/contact" },
  // Otentica is de screeningsleverancier achter /screening.
  { from: "merk/otentica", to: "/screening" },
  { from: "vacature-administrateur", to: "/over-ons" },
  { from: "verheij-groep-bv", to: "/over-ons" },
  { from: "test-2", to: "/" },

  // --- Ronde 3 (SEO-audit 1-10-2026): alle oude URL's uit het internetarchief ---
  // Gegenereerd: artikel > onderwerp-pagina > kennisbankcategorie > /kennisbank.
  { from: "10-tips-voor-een-digitaal-veilig-bedrijf", to: "/kennisbank" },
  { from: "6-hittetips-voor-een-productieve-dag-op-kantoor", to: "/kennisbank" },
  { from: "6-nieuwe-belastingmaatregelen-voor-ondernemers", to: "/kennisbank/belastingen" },
  { from: "8-tips-om-betalingsproblemen-te-voorkomen", to: "/kennisbank/financien" },
  { from: "aanmeldformulier-cyberactie-bav", to: "/verzekeringen" },
  { from: "aanmeldformulier-cyberactie-data", to: "/verzekeringen" },
  { from: "aanmeldformulier-cyberactie-golf", to: "/verzekeringen" },
  { from: "aanmeldformulier-ictu-bav", to: "/verzekeringen" },
  { from: "aansprakelijkheidsverzekering-zzp", to: "/verzekeringen" },
  { from: "aantal-fulltime-opdrachten-zzper-daalt", to: "/kennisbank" },
  { from: "academy", to: "/over-ons" },
  { from: "advies-zzp", to: "/diensten" },
  { from: "all-in", to: "/verzekeringen" },
  { from: "allin-bedanktpage", to: "/verzekeringen" },
  { from: "aov-movir", to: "/aov" },
  { from: "arbeidongeschiktheidsverzekering", to: "/aov" },
  { from: "arbeidongeschiktheidsverzekering-cb", to: "/aov" },
  { from: "arbeidongeschiktheidsverzekering-mo", to: "/aov" },
  { from: "arbeidsongeschiktheidsverzekering", to: "/aov" },
  { from: "arbeidsongeschiktheidsverzekering-m", to: "/aov" },
  { from: "arbeidsongeschiktheidsvoorziening-s", to: "/aov" },
  { from: "author/infokasunmedia-nl", to: "/over-ons" },
  { from: "author/infokasunmedia-nl/page/2", to: "/over-ons" },
  { from: "author/infokasunmedia-nl/page/3", to: "/over-ons" },
  { from: "author/infokasunmedia-nl/page/4", to: "/over-ons" },
  { from: "author/zp_admin", to: "/over-ons" },
  { from: "bav-bedankt", to: "/verzekeringen" },
  { from: "bav-bedanktpage", to: "/verzekeringen" },
  { from: "bav-hrm", to: "/verzekeringen" },
  { from: "bav-inschrijfformulier", to: "/verzekeringen" },
  { from: "bav-it", to: "/verzekeringen" },
  { from: "bav-marketing", to: "/verzekeringen" },
  { from: "bav-overall", to: "/verzekeringen" },
  { from: "bav-overstapformulier", to: "/verzekeringen" },
  { from: "bedankt-nk-golf-voor-zpers-2018", to: "/verzekeringen" },
  { from: "beroeps-en-bedrijfsaansprakelijkheidsverzekering", to: "/verzekeringen" },
  { from: "beroeps-en-bedrijfsaansprakelijkheidsverzekering-nodig-of-niet", to: "/verzekeringen" },
  { from: "betweenstaffing", to: "/partners" },
  { from: "beweeg-je-stress-weg", to: "/mentale-gezondheid" },
  { from: "blog-tarief-hoogopgeleide-zzper-piekt-op-65-jarige-leeftijd", to: "/kennisbank" },
  { from: "brancheverklaring", to: "/verzekeringen" },
  { from: "btw-aangifte-waar-moet-je-aan-denken", to: "/kennisbank/belastingen" },
  { from: "btw-nummer-van-nihil-aangevers-wordt-ingetrokken", to: "/kennisbank/belastingen" },
  { from: "category/arbeidsongeschiktheid", to: "/aov" },
  { from: "category/cyber", to: "/verzekeringen" },
  { from: "category/financieel", to: "/kennisbank/financien" },
  { from: "category/financieel/page/2", to: "/kennisbank/financien" },
  { from: "category/juridisch", to: "/kennisbank/wet-en-regelgeving" },
  { from: "category/mobiliteit", to: "/kennisbank/belastingen" },
  { from: "category/ontwikkeling", to: "/kennisbank/ondernemen" },
  { from: "category/pensioen", to: "/pensioen" },
  { from: "category/uncategorized", to: "/kennisbank" },
  { from: "category/verzekeringen", to: "/verzekeringen" },
  { from: "category/zelfstandig-professional", to: "/kennisbank/ondernemen" },
  { from: "category/zelfstandig-professional/page/2", to: "/kennisbank/ondernemen" },
  { from: "category/zp-golf", to: "/kennisbank" },
  { from: "control", to: "/creditcontrol" },
  { from: "control/advies", to: "/creditcontrol" },
  { from: "control/algemene-voorwaarden", to: "/creditcontrol" },
  { from: "control/bav", to: "/creditcontrol" },
  { from: "control/contact", to: "/creditcontrol" },
  { from: "control/faq", to: "/creditcontrol" },
  { from: "control/financieel", to: "/creditcontrol" },
  { from: "control/financieel/financiele-analyse", to: "/creditcontrol" },
  { from: "control/financieel/hypotheek-advies", to: "/creditcontrol" },
  { from: "control/financieel/subsidie-check", to: "/creditcontrol" },
  { from: "control/over-zp-control", to: "/creditcontrol" },
  { from: "control/privacy-statement", to: "/creditcontrol" },
  { from: "control/verzekeringen", to: "/creditcontrol" },
  { from: "control/verzekeringen/bav", to: "/creditcontrol" },
  { from: "cookie-instellingen-1", to: "/cookies" },
  { from: "cyber-bedanktpage", to: "/verzekeringen" },
  { from: "cyber-verzekering-zzp", to: "/verzekeringen" },
  { from: "cyberclear-inschrijfformulier", to: "/verzekeringen" },
  { from: "decemberactie", to: "/verzekeringen" },
  { from: "dienstverlening", to: "/diensten" },
  { from: "een-tip-hoe-je-fiscaal-voordeel-van-2020-kunt-benutten", to: "/kennisbank/belastingen" },
  { from: "en/6-nieuwe-belastingmaatregelen-voor-ondernemers", to: "/kennisbank/belastingen" },
  { from: "en/author/infokasunmedia-nl/page/4", to: "/over-ons" },
  { from: "en/beroeps-en-bedrijfsaansprakelijkheidsverzekering", to: "/verzekeringen" },
  { from: "en/category/cyber", to: "/verzekeringen" },
  { from: "en/dienstverlening", to: "/diensten" },
  { from: "en/een-tip-hoe-je-fiscaal-voordeel-van-2020-kunt-benutten", to: "/kennisbank/belastingen" },
  { from: "en/feed-2", to: "/kennisbank" },
  { from: "en/financien", to: "/kennisbank" },
  { from: "en/financien/factoring", to: "/creditcontrol" },
  { from: "en/financien/factoring/factorscan", to: "/creditcontrol" },
  { from: "en/financien/jaarruimte-berekenen", to: "/pensioen" },
  { from: "en/financien/pensioen-zzp", to: "/pensioen" },
  { from: "en/financien/pensioengat-reserveringsruimte-berekenen", to: "/pensioen" },
  { from: "en/financien/subsidie-check", to: "/kennisbank/financien" },
  { from: "en/gevaar-voor-cybercriminelen-die-misbruik-maken-van-thuiswerken", to: "/verzekeringen" },
  { from: "en/hackers-maken-gebruik-van-de-pandemie-hoe-houd-jij-ze-tegen", to: "/kennisbank" },
  { from: "en/je-risicos-in-kaart-brengen-noodzakelijk", to: "/kennisbank" },
  { from: "en/je-risicos-in-kaart-brengen-noodzakelijk-2", to: "/kennisbank" },
  { from: "en/jouw-vangnet-bij-arbeidsongeschiktheid-al-voor-1-euro-per-dag", to: "/aov" },
  { from: "en/juridisch", to: "/kennisbank/wet-en-regelgeving" },
  { from: "en/juridisch/adviesdesk-zzp", to: "/kennisbank/wet-en-regelgeving" },
  { from: "en/juridisch/documenten-selfservice-das", to: "/kennisbank/wet-en-regelgeving" },
  { from: "en/juridisch/gevolgrecht-zzp", to: "/kennisbank/wet-en-regelgeving" },
  { from: "en/lidmaatschap", to: "/collectieve-inkoop" },
  { from: "en/losgeldverbod-voor-ransomware-wordt-onderzocht", to: "/kennisbank" },
  { from: "en/metform-form/new-form-1618404580", to: "/en" },
  { from: "en/metform-form/subsidiecheck", to: "/en" },
  { from: "en/mobiliteitskaart-zzp", to: "/kennisbank/belastingen" },
  { from: "en/nieuws", to: "/kennisbank" },
  { from: "en/nk-golftoernooi-voor-zpers-2020-geannuleerd", to: "/" },
  { from: "en/nooit-meer-bonnetjes-bewaren", to: "/kennisbank/financien" },
  { from: "en/oeps", to: "/en" },
  { from: "en/partners/between-staffing", to: "/partners" },
  { from: "en/partners/headfirst", to: "/partners" },
  { from: "en/partners/staffing-ms", to: "/partners" },
  { from: "en/prinsjesdag-2020-wat-betekent-dit-voor-jou-als-zper", to: "/kennisbank/belastingen" },
  { from: "en/product/beroeps-en-bedrijfsaansprakelijkheidsverzekering", to: "/verzekeringen" },
  { from: "en/slimme-manieren-om-je-pensioen-te-regelen-als-zzper", to: "/pensioen" },
  { from: "en/subsidie-voor-zpers", to: "/kennisbank/financien" },
  { from: "en/tegemoetkoming-vaste-lasten-mkb-tvl-vanaf-nu-aan-te-vragen", to: "/kennisbank" },
  { from: "en/tweede-voortgangsbrief-kabinet-vervanging-wet-dba-nogmaals-uitgesteld", to: "/kennisbank/wet-en-regelgeving" },
  { from: "en/verzekeringen/arbeidsongeschiktheid-zzp", to: "/aov" },
  { from: "en/verzekeringen/arbeidsongeschiktheid-zzp/centraalbeheer", to: "/aov" },
  { from: "en/verzekeringen/arbeidsongeschiktheid-zzp/sharepeople", to: "/aov" },
  { from: "en/verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering", to: "/verzekeringen" },
  { from: "en/verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/actie-bedankt", to: "/verzekeringen" },
  { from: "en/verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/bedankt", to: "/verzekeringen" },
  { from: "en/verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/hrm-actie", to: "/verzekeringen" },
  { from: "en/verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/it-actie", to: "/verzekeringen" },
  { from: "en/verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/marketing-actie", to: "/verzekeringen" },
  { from: "en/verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/overall-actie", to: "/verzekeringen" },
  { from: "en/verzekeringen/collectieve-zorgverzekering", to: "/zorgverzekering" },
  { from: "en/verzekeringen/cyber-clear-verzekering", to: "/verzekeringen" },
  { from: "en/verzekeringen/cyber-clear-verzekering/bedankt", to: "/verzekeringen" },
  { from: "en/woningmarkt-voor-zzpers-op-slot", to: "/kennisbank" },
  { from: "en/zp-academy", to: "/over-ons" },
  { from: "en/zp-golf", to: "/" },
  { from: "en/zp-zaken", to: "/kennisbank/zp-zaken" },
  { from: "en/zzper-reist-drie-keer-zo-ver-als-gemiddelde-nederlander", to: "/kennisbank" },
  { from: "factorscan", to: "/creditcontrol" },
  { from: "facts", to: "/" },
  { from: "facts/contact", to: "/contact" },
  { from: "facts/edities", to: "/" },
  { from: "facts/faq", to: "/faq" },
  { from: "facts/pers", to: "/" },
  { from: "facts/privacy-statement", to: "/cookies" },
  { from: "feed-2", to: "/kennisbank" },
  { from: "fijne-feestdagen", to: "/" },
  { from: "financieel-advies-zzp", to: "/kennisbank/financien" },
  { from: "financieleanalyse", to: "/kennisbank/financien" },
  { from: "financien/factoring", to: "/creditcontrol" },
  { from: "financien/factoring/factorscan", to: "/creditcontrol" },
  { from: "financien/pensioen-zzp", to: "/pensioen" },
  { from: "financien/subsidie-check", to: "/kennisbank/financien" },
  { from: "gevaar-voor-cybercriminelen-die-misbruik-maken-van-thuiswerken", to: "/verzekeringen" },
  { from: "gevolgrecht", to: "/kennisbank/wet-en-regelgeving" },
  { from: "go/beroepsaansprakelijkheid-voorwaarden-kantoorrisico", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "go/coaches-verzekeringskaart-beroepsaansprakelijkheid", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "go/overige-zakelijke-dienstverlening-polisvoorwaarden-beroepsaansprakelijkheid", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "golf", to: "/" },
  { from: "golf/nk", to: "/" },
  { from: "hackers-maken-gebruik-van-de-pandemie-hoe-houd-jij-ze-tegen", to: "/kennisbank" },
  { from: "headfirst", to: "/partners" },
  { from: "headfirst-bav", to: "/partners" },
  { from: "headfirst-bav-bedanktpage", to: "/partners" },
  { from: "headfirst-bav-inschrijfform", to: "/partners" },
  { from: "het-nk-golftoernooi-voor-zpers-2019-burggolf-de-haverleij", to: "/" },
  { from: "home/nieuws", to: "/kennisbank" },
  { from: "ict-brochure-beroepsaansprakelijkheid", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "ict-polisvoorwaarden-beroepsaansprakelijkheid", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "infographic-wie-is-de-zper-in-de-zakelijke-dienstverlening", to: "/diensten" },
  { from: "inschrijfformulier-bav", to: "/verzekeringen" },
  { from: "inschrijven", to: "/" },
  { from: "je-risicos-in-kaart-brengen-noodzakelijk", to: "/kennisbank" },
  { from: "je-risicos-in-kaart-brengen-noodzakelijk-2", to: "/kennisbank" },
  { from: "jouw-vangnet-bij-arbeidsongeschiktheid-al-voor-1-euro-per-dag", to: "/aov" },
  { from: "juridisch", to: "/kennisbank/wet-en-regelgeving" },
  { from: "juridisch/adviesdesk-zzp", to: "/kennisbank/wet-en-regelgeving" },
  { from: "juridisch/gevolgrecht-zzp", to: "/kennisbank/wet-en-regelgeving" },
  { from: "juridischadvies", to: "/kennisbank/wet-en-regelgeving" },
  { from: "kopie-van-financieel-pensioen", to: "/pensioen" },
  { from: "kopie-van-nk-golf-inschrijfformulie", to: "/verzekeringen" },
  { from: "kopie-van-nk-golf-inschrijfformulie-1", to: "/verzekeringen" },
  { from: "lidmaatschap", to: "/collectieve-inkoop" },
  { from: "lidmaatschappen", to: "/collectieve-inkoop" },
  { from: "losgeldverbod-voor-ransomware-wordt-onderzocht", to: "/kennisbank" },
  { from: "management-consultancy-brochure-beroepsaansprakelijkheid", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "management-consultancy-verzekeringskaart-beroepsaansprakelijkheid", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "meerwerk-zo-voorkom-je-een-discussie", to: "/kennisbank" },
  { from: "mils-onderzoek", to: "/mentale-gezondheid" },
  { from: "milsonderzoek-inschrijven", to: "/mentale-gezondheid" },
  { from: "mobiliteitskaart", to: "/kennisbank/belastingen" },
  { from: "mobiliteitskaart-zzp", to: "/kennisbank/belastingen" },
  { from: "movir-coming-soon", to: "/aov" },
  { from: "nieuws/categories/arbeidsongeschiktheid", to: "/aov" },
  { from: "nieuws/categories/bav", to: "/verzekeringen" },
  { from: "nieuws/categories/coronacrisis", to: "/kennisbank" },
  { from: "nieuws/categories/cybercrime", to: "/verzekeringen" },
  { from: "nieuws/categories/financieel", to: "/kennisbank/financien" },
  { from: "nieuws/categories/partner", to: "/partners" },
  { from: "nieuws/categories/pensioen", to: "/pensioen" },
  { from: "nieuws/categories/zorgverzekering", to: "/zorgverzekering" },
  { from: "nieuws/categories/zzp", to: "/kennisbank/ondernemen" },
  { from: "nieuws/page/2", to: "/kennisbank" },
  { from: "nieuws/page/3", to: "/kennisbank" },
  { from: "nieuws/page/4", to: "/kennisbank" },
  { from: "nieuws/page/5", to: "/kennisbank" },
  { from: "nieuws/page/6", to: "/kennisbank" },
  { from: "nieuws/tags/aov", to: "/aov" },
  { from: "nieuws/tags/ondernemen", to: "/kennisbank/ondernemen" },
  { from: "nieuws/tags/partner", to: "/partners" },
  { from: "nieuws/tags/zzp", to: "/kennisbank/ondernemen" },
  { from: "nk-golf-inschrijfformulier", to: "/verzekeringen" },
  { from: "nk-golf-voor-zpers-2018-de-aftermovie", to: "/" },
  { from: "nk-golftoernooi-voor-zpers-2020-geannuleerd", to: "/" },
  { from: "nooit-meer-bonnetjes-bewaren", to: "/kennisbank/financien" },
  { from: "online-lifestyle-plan", to: "/mentale-gezondheid" },
  { from: "onlinelifestyleplan-inschrijven", to: "/mentale-gezondheid" },
  { from: "onvz", to: "/zorgverzekering" },
  { from: "opleidingen-en-trainingen", to: "/over-ons" },
  { from: "over-zpzaken", to: "/over-ons" },
  { from: "overzp", to: "/over-ons" },
  { from: "paasactie", to: "/verzekeringen" },
  { from: "partners/between-staffing", to: "/partners" },
  { from: "partners/headfirst", to: "/partners" },
  { from: "partners/staffing-ms", to: "/partners" },
  { from: "persoonlijke-ontwikkeling", to: "/over-ons" },
  { from: "post/10-tips-voor-een-digitaal-veilig-bedrijf", to: "/kennisbank" },
  { from: "post/2018-biedt-positief-vooruitzicht-voor-zelfstandig-professionals", to: "/kennisbank" },
  { from: "post/40-uren-contract-steeds-uitzonderlijker-voor-zzp-er-bij-overheid", to: "/kennisbank" },
  { from: "post/6-hittetips", to: "/kennisbank" },
  { from: "post/6-nieuwe-belastingmaatregelen", to: "/kennisbank/belastingen" },
  { from: "post/6-tips-voor-opstellen-ideale-factuur", to: "/kennisbank/financien" },
  { from: "post/8-feiten-over-de-zp-markt", to: "/kennisbank" },
  { from: "post/8-tips-om-betalingsproblemen-te-voorkomen", to: "/kennisbank/financien" },
  { from: "post/aanmanen-dit-zijn-de-regels", to: "/kennisbank" },
  { from: "post/aantal-opdrachten-zzp-er-stijgt-met-30-procent", to: "/kennisbank" },
  { from: "post/achtergrond-wet-dba", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/aov-sharepeople-korting", to: "/aov" },
  { from: "post/basisverzekering-geeft-meer-vrijheid", to: "/verzekeringen" },
  { from: "post/belastingdienst-meldt-dat-het-btw-nummer-wordt-ingetrokken-van-nihil-aangevers", to: "/kennisbank/belastingen" },
  { from: "post/beroeps-en-bedrijfsaansprakelijkheidsverzekering-nodig-of-niet", to: "/verzekeringen" },
  { from: "post/beter-leren-door-digitalisering", to: "/kennisbank" },
  { from: "post/beweeg-je-stress-weg", to: "/mentale-gezondheid" },
  { from: "post/bewust-werken-in-de-cloud-de-risico-s-in-kaart-gebracht-1", to: "/kennisbank" },
  { from: "post/blogupdates-forse-maatregelen-voor-bedrijven-en-zzp-werktijdverkorting-vervalt", to: "/kennisbank" },
  { from: "post/btw-aangifte-waar-moet-je-aan-denken", to: "/kennisbank/belastingen" },
  { from: "post/cybercriminaliteit-pandemie-voorkomen", to: "/verzekeringen" },
  { from: "post/de-beroeps-en-bedrijfsaansprakelijkheidsverzekering", to: "/verzekeringen" },
  { from: "post/een-eigen-zaak-het-belang-en-gebruik-van-algemene-voorwaarden", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "post/een-tip-hoe-je-fiscaal-voordeel-van-2020-kunt-benutten", to: "/kennisbank/belastingen" },
  { from: "post/er-is-altijd-een-reden-om-te-flexibiliseren", to: "/kennisbank" },
  { from: "post/er-is-altijd-een-reden-om-te-flexibiliseren-1", to: "/kennisbank" },
  { from: "post/ervaring-belangrijker-dan-prijs-bij-selectie-zzp-ers", to: "/kennisbank" },
  { from: "post/fijne-feestdagen", to: "/" },
  { from: "post/flexibele-arbeid-in-kaart-gebracht", to: "/kennisbank" },
  { from: "post/geld-verdienen-door-beter-debiteurenbeheer-fabel-of-niet", to: "/kennisbank" },
  { from: "post/gevaar-voor-cybercriminelen-die-misbruik-maken-van-thuiswerken", to: "/verzekeringen" },
  { from: "post/gratis-webinar-over-pensioen-en-financi\u00eble-analyse", to: "/pensioen" },
  { from: "post/gratis-webinar-wat-kun-je-zelf-doen-aan-je-pensioen-als-zp-er", to: "/pensioen" },
  { from: "post/handhaving-wet-dba-opgeschort-tot-1-januari-2020", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/heb-ik-een-aansprakelijkheidsverzekering-nodig", to: "/verzekeringen" },
  { from: "post/het-nk-golftoernooi-voor-zp-ers-burggolf-de-haverleij", to: "/" },
  { from: "post/hoe-gaat-het-met-de-var-vervanger", to: "/kennisbank" },
  { from: "post/hoogopgeleide-zzp-ers-massaal-getroffen-door-de-wet-dba", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/infographic-wie-is-de-zp-er-in-de-zakelijke-dienstverlening", to: "/diensten" },
  { from: "post/invest-now-earn-later", to: "/kennisbank" },
  { from: "post/is-een-beroeps-en-bedrijfsaansprakelijkheidsverzekering-een-modeverschijnsel-of-noodzakelijk-kwaad", to: "/verzekeringen" },
  { from: "post/jongste-generatie-werkenden-is-meant-to-be-flex", to: "/kennisbank" },
  { from: "post/jouw-update-over-ondernemerschap-gericht-op-de-zelfstandig-professional", to: "/kennisbank" },
  { from: "post/kwart-zzp-ers-overweegt-te-stoppen-door-wet-dba", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/linkedin-is-de-netwerkborrel-facebook-de-kroeg", to: "/kennisbank" },
  { from: "post/marktmonitor-zp-facts-positief-gestemd-over-zzp-markt-in-2016", to: "/" },
  { from: "post/meerwerk-zo-voorkom-je-een-discussie", to: "/kennisbank" },
  { from: "post/modern-day-meetings", to: "/kennisbank" },
  { from: "post/nieuwe-var-scheidt-kaf-van-het-koren", to: "/kennisbank" },
  { from: "post/nieuwe-voortgangsbrief-kabinet-belastingdienst-bezoekt-honderd-organisaties-in-2018", to: "/kennisbank/belastingen" },
  { from: "post/nk-golftoernooi-voor-zpers-2020-geannuleerd", to: "/" },
  { from: "post/nooit-meer-bonnetjes-bewaren", to: "/kennisbank/financien" },
  { from: "post/ondernemers-risico-in-kaart-brengen-noodzakelijk", to: "/kennisbank" },
  { from: "post/onderzoek-4-op-de-10-zzp-ers-matig-tot-slecht-online-beveiligd", to: "/kennisbank" },
  { from: "post/persbericht-2018-biedt-positief-vooruitzicht-voor-zelfstandig-professionals", to: "/kennisbank" },
  { from: "post/persbericht-aantal-fulltime-opdrachten-zzp-er-daalt", to: "/kennisbank" },
  { from: "post/persbericht-bv-verliest-aan-populariteit-onder-zzp-ers", to: "/kennisbank" },
  { from: "post/persbericht-steeds-minder-fulltime-opdrachten-zzp-er", to: "/kennisbank" },
  { from: "post/persbericht-zzp-er-geeft-zichzelf-ruime-8-voor-kennisdeling-met-opdrachtgever", to: "/kennisbank" },
  { from: "post/precies-weten-hoe-je-er-financieel-voor-staat-als-zp-er", to: "/kennisbank/financien" },
  { from: "post/prinsjesdag-2020-wat-betekent-dit-voor-jou-als-zp-er", to: "/kennisbank/belastingen" },
  { from: "post/priv\u00e9-verzekering-is-niet-genoeg", to: "/verzekeringen" },
  { from: "post/samenwerking-zpzaken-en-zilverenkruis", to: "/kennisbank" },
  { from: "post/steeds-jonger-startende-zzp-er-is-geen-schijnzelfstandige", to: "/kennisbank" },
  { from: "post/subsidie-voor-zp-ers", to: "/kennisbank/financien" },
  { from: "post/tarief-hoogopgeleide-zzp-er-piekt-op-56-jarige-leeftijd", to: "/kennisbank" },
  { from: "post/tegemoetkoming-vaste-lasten-mkb-tvl-vanaf-nu-aan-te-vragen", to: "/kennisbank" },
  { from: "post/time-is-money", to: "/kennisbank" },
  { from: "post/time-is-money-1", to: "/kennisbank" },
  { from: "post/tips-voor-veilig-en-professioneel-thuiswerken", to: "/kennisbank" },
  { from: "post/tweede-voortgangsbrief-kabinet-vervanging-wet-dba-nogmaals-uitgesteld", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/uitstellen-is-kostbaar", to: "/kennisbank" },
  { from: "post/universiteit-van-tilburg-en-headfirst-introduceren-index-voor-zzp-markt", to: "/partners" },
  { from: "post/uurtarief-zelfstandig-professional-daalt-onder-druk-wet-dba", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/uurtarief-zelfstandig-professional-daalt-onder-druk-wet-dba-1", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/vacature-operations-communicatie", to: "/kennisbank" },
  { from: "post/valentijns-date-voor-vrijgezelle-it-ers", to: "/kennisbank" },
  { from: "post/vanuit-je-bv-een-deel-van-je-hypotheek-financieren-het-kan", to: "/kennisbank/financien" },
  { from: "post/veel-media-aandacht-voor-onderzoeksresultaten-wet-dba-opiniemonitor", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/verzekeren-tegen-cybercrime-is-een-must", to: "/verzekeringen" },
  { from: "post/vragen-en-antwoorden-over-de-verplichte-aov-voor-zp-ers", to: "/aov" },
  { from: "post/wat-betekent-het-pensioenakkoord-voor-zzp-ers-en-ondernemers", to: "/pensioen" },
  { from: "post/wat-gebeurt-er-als-je-ziek-wordt", to: "/kennisbank" },
  { from: "post/webinar-pensioenoplossing", to: "/pensioen" },
  { from: "post/welke-verzekeringen-moet-ik-hebben", to: "/kennisbank/welke-verzekeringen-zzp" },
  { from: "post/werken-in-de-cloud", to: "/kennisbank" },
  { from: "post/wet-dba-op-de-schop-introductie-opdrachtgeversverklaring", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/wet-dba-op-de-schop-introductie-opdrachtgeversverklaring-1", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/woningmarkt-voor-zzp-ers-op-slot", to: "/kennisbank" },
  { from: "post/word-jij-onze-nieuwe-commerci\u00eble-medewerker-voor-zp-radio", to: "/" },
  { from: "post/zorgen-onder-zzp-ers-groot-ondanks-uitstel-handhaving-wet-dba", to: "/kennisbank/wet-en-regelgeving" },
  { from: "post/zorgen-zzp-ers-om-wetswijzigingen", to: "/kennisbank" },
  { from: "post/zp-facts-gevolgen-van-avg-vrijwel-onbekend-onder-zzp-ers", to: "/" },
  { from: "post/zp-facts-uurtarief-zzp-er-krabbelt-op", to: "/" },
  { from: "post/zp-golf-organiseert-netwerkbijeenkomt", to: "/" },
  { from: "post/zp-mobiliteitskaart-d\u00e9-mobiliteitsoplossing-voor-zp-ers", to: "/kennisbank/belastingen" },
  { from: "post/zp-trends-de-belangrijkste-ontwikkelingen-in-2016", to: "/kennisbank" },
  { from: "post/zzp-er-potentieel-grote-bron-van-werkgelegenheid", to: "/kennisbank" },
  { from: "post/zzp-er-reist-drie-keer-zo-ver-als-gemiddelde-nederlander", to: "/kennisbank" },
  { from: "post/zzp-ers-verdienen-flexibiliteit-maatwerk-en-kwaliteit", to: "/kennisbank" },
  { from: "post/zzp-ers-zien-gouden-kansen-in-nieuwe-technologie\u00ebn", to: "/kennisbank" },
  { from: "post/\u00e9\u00e9n-op-de-tien-zzp-ers-mist-uitdaging-in-zijn-opdracht", to: "/kennisbank" },
  { from: "prinsjesdag-2020-wat-betekent-dit-voor-jou-als-zper", to: "/kennisbank/belastingen" },
  { from: "product-category/uncategorized", to: "/kennisbank" },
  { from: "product-tag/bav", to: "/verzekeringen" },
  { from: "product/beroeps-en-bedrijfsaansprakelijkheidsverzekering", to: "/verzekeringen" },
  { from: "profiteer-mee-van-de-collectieve-zorgverzekering-van-zilveren-kruis", to: "/zorgverzekering" },
  { from: "prosci-change-management", to: "/kennisbank" },
  { from: "radio", to: "/" },
  { from: "radio/show/de-gig-economy-volgens-leonard-millenaar", to: "/" },
  { from: "registreer", to: "/" },
  { from: "risicoscan-zzp", to: "/kennisbank" },
  { from: "salarisadministratie-zzp", to: "/kennisbank" },
  { from: "scrum", to: "/" },
  { from: "services", to: "/" },
  { from: "services/advies", to: "/diensten" },
  { from: "services/algemene-voorwaarden", to: "/documenten#verzekeringsvoorwaarden" },
  { from: "services/bav", to: "/verzekeringen" },
  { from: "services/contact", to: "/contact" },
  { from: "services/financieel", to: "/kennisbank/financien" },
  { from: "services/over-zp-services", to: "/kennisbank" },
  { from: "services/privacy-statement", to: "/cookies" },
  { from: "services/verzekeringen", to: "/verzekeringen" },
  { from: "shift-happens-trail", to: "/kennisbank" },
  { from: "shifthappenstrail-inschrijven", to: "/kennisbank" },
  { from: "slimme-manieren-om-je-pensioen-te-regelen-als-zzper", to: "/pensioen" },
  { from: "staffingms", to: "/partners" },
  { from: "startup", to: "/" },
  { from: "startup-bedanktpage", to: "/verzekeringen" },
  { from: "subsidie-voor-zpers", to: "/kennisbank/financien" },
  { from: "subsidiecheck", to: "/kennisbank/financien" },
  { from: "tegemoetkoming-vaste-lasten-mkb-tvl-vanaf-nu-aan-te-vragen", to: "/kennisbank" },
  { from: "tips-voor-veilig-en-professioneel-thuiswerken", to: "/kennisbank" },
  { from: "tweede-voortgangsbrief-kabinet-vervanging-wet-dba-nogmaals-uitgesteld", to: "/kennisbank/wet-en-regelgeving" },
  { from: "under-construction-zp-radio", to: "/" },
  { from: "universiteit-van-tilburg-en-headfirst-introduceren-index-voor-zzp-markt", to: "/partners" },
  { from: "vacatures", to: "/" },
  { from: "verzekering-myler-bav", to: "/verzekeringen" },
  { from: "verzekeringen/arbeidsongeschiktheid-zzp", to: "/aov" },
  { from: "verzekeringen/arbeidsongeschiktheid-zzp/centraalbeheer", to: "/aov" },
  { from: "verzekeringen/arbeidsongeschiktheid-zzp/sharepeople", to: "/aov" },
  { from: "verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering", to: "/verzekeringen" },
  { from: "verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/actie-bedankt", to: "/verzekeringen" },
  { from: "verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/bedankt", to: "/verzekeringen" },
  { from: "verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/hrm-actie", to: "/verzekeringen" },
  { from: "verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/it-actie", to: "/verzekeringen" },
  { from: "verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/marketing-actie", to: "/verzekeringen" },
  { from: "verzekeringen/beroeps-en-bedrijfsaansprakelijkheidsverzekering/overall-actie", to: "/verzekeringen" },
  { from: "verzekeringen/collectieve-zorgverzekering", to: "/zorgverzekering" },
  { from: "verzekeringen/cyber-clear-verzekering", to: "/verzekeringen" },
  { from: "verzekeringen/cyber-clear-verzekering/bedankt", to: "/verzekeringen" },
  { from: "verzekeringen/cyberclear-cyber-verzekering", to: "/verzekeringen" },
  { from: "verzekeringsadvies", to: "/verzekeringen" },
  { from: "verzekeringsgids", to: "/verzekeringen" },
  { from: "vraagbaak", to: "/" },
  { from: "vragen-en-antwoorden-over-de-verplichte-aov-voor-zpers", to: "/aov" },
  { from: "wat-betekent-het-pensioenakkoord-voor-zzpers-en-ondernemers", to: "/pensioen" },
  { from: "webinar-brightpensioen", to: "/pensioen" },
  { from: "wijzigingsformulier", to: "/" },
  { from: "woningmarkt-voor-zzpers-op-slot", to: "/kennisbank" },
  { from: "zes-tips-voor-opstellen-ideale-factuur", to: "/kennisbank/financien" },
  { from: "zorg-overstapformulier", to: "/kennisbank" },
  { from: "zorgenzekerheid", to: "/" },
  { from: "zp-academy", to: "/over-ons" },
  { from: "zp-academy-under-construction", to: "/over-ons" },
  { from: "zp-golf", to: "/" },
  { from: "zp-zaken", to: "/kennisbank/zp-zaken" },
  { from: "zpradio", to: "/" },
  { from: "zpradio-podcast", to: "/" },
  { from: "zzper-reist-drie-keer-zo-ver-als-gemiddelde-nederlander", to: "/kennisbank" },
  { from: "zzpers-zien-gouden-kansen-in-nieuwe-technologieen", to: "/kennisbank" },
];

/**
 * Kennisbank-categoriepagina per categoriewaarde zoals die in de database
 * staat. Alleen deze vier categoriepagina's bestaan als route; alle overige
 * categorieën vallen terug op het kennisbankoverzicht.
 */
export const CATEGORY_PAGES: Record<string, string> = {
  fiscaal: "/kennisbank/belastingen",
  belastingen: "/kennisbank/belastingen",
  financien: "/kennisbank/financien",
  "financiën": "/kennisbank/financien",
  regelgeving: "/kennisbank/wet-en-regelgeving",
  wetgeving: "/kennisbank/wet-en-regelgeving",
  "wet-en-regelgeving": "/kennisbank/wet-en-regelgeving",
  ondernemen: "/kennisbank/ondernemen",
};

/** Categoriepagina voor een categoriewaarde, of /kennisbank als die niet bestaat. */
export function categoryPageFor(category?: string | null): string {
  if (!category) return "/kennisbank";
  return CATEGORY_PAGES[category.trim().toLowerCase()] || "/kennisbank";
}

export interface ArticleRedirectInfo {
  slug: string;
  category: string | null;
  is_published: boolean;
}

/**
 * Bestemming voor één legacy-URL, gegeven de artikelen uit de database.
 * - gepubliceerd artikel met dezelfde slug → /kennisbank/<slug>
 * - conceptartikel met dezelfde slug       → categoriepagina (of /kennisbank)
 * - geen artikel                           → handmatige bestemming
 */
export function resolveRedirectTarget(
  redirect: LegacyRedirect,
  articles: Map<string, ArticleRedirectInfo>,
): string {
  const article = articles.get(redirect.from);
  if (!article) return redirect.to;
  if (article.is_published) return `/kennisbank/${article.slug}`;
  return categoryPageFor(article.category);
}
