import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, rgb, StandardFonts } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;

    // Verify the user is a team member
    const userClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: { user }, error: authError } = await userClient.auth.getUser();
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Check team membership
    const { data: isTeam } = await createClient(supabaseUrl, supabaseServiceKey)
      .rpc("is_team_member", { _user_id: user.id });
    if (!isTeam) {
      return new Response(JSON.stringify({ error: "Forbidden" }), {
        status: 403,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { lead_id, policy_data } = await req.json();
    if (!lead_id && !policy_data) {
      return new Response(JSON.stringify({ error: "lead_id or policy_data required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const adminClient = createClient(supabaseUrl, supabaseServiceKey);

    // Get lead data if lead_id provided
    let data = policy_data;
    if (lead_id && !data) {
      const { data: lead, error: leadError } = await adminClient
        .from("leads")
        .select("*")
        .eq("id", lead_id)
        .maybeSingle();
      if (leadError || !lead) {
        return new Response(JSON.stringify({ error: "Lead not found" }), {
          status: 404,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      data = {
        certificate_holder: lead.bedrijfsnaam || `${lead.voornaam} ${lead.achternaam}`,
        insured_name: `${lead.voornaam} ${lead.achternaam}`,
        start_date: lead.ingangsdatum || new Date().toISOString().split("T")[0],
        profession: lead.beroep || "Onbekend",
        package_type: lead.verzekering_type || "Combi Uitgebreid",
      };
    }

    // Insert policy record (certificate_number auto-generated by trigger)
    const { data: policy, error: policyError } = await adminClient
      .from("policies")
      .insert({
        lead_id: lead_id || null,
        certificate_number: "",
        certificate_holder: data.certificate_holder,
        insured_name: data.insured_name,
        start_date: data.start_date,
        profession: data.profession,
        package_type: data.package_type || "Combi Uitgebreid",
        bav_per_event: data.bav_per_event || "€ 5.000.000",
        bav_per_year: data.bav_per_year || "€ 15.000.000",
        avb_per_event: data.avb_per_event || "€ 2.500.000",
        avb_per_year: data.avb_per_year || "€ 5.000.000",
        issued_by: data.issued_by || "Michel Verheij",
      })
      .select()
      .single();

    if (policyError) {
      console.error("Policy insert error:", policyError);
      return new Response(JSON.stringify({ error: "Failed to create policy", details: policyError.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Generate PDF
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]); // A4
    const { width, height } = page.getSize();

    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);

    const darkRed = rgb(0.7, 0.1, 0.1);
    const black = rgb(0, 0, 0);
    const gray = rgb(0.4, 0.4, 0.4);
    const lightGray = rgb(0.85, 0.85, 0.85);

    const leftMargin = 60;
    const labelX = leftMargin;
    const valueX = 220;
    let y = height - 60;

    // Header - ZP Zaken logo text
    page.drawText("ZP", { x: leftMargin + 10, y: y - 5, size: 28, font: helveticaBold, color: darkRed });
    page.drawText("Zaken", { x: leftMargin + 50, y: y - 5, size: 18, font: helvetica, color: black });

    y -= 50;

    // Title
    page.drawText("VERZEKERINGSCERTIFICAAT", {
      x: leftMargin, y, size: 16, font: helveticaBold, color: darkRed,
    });
    y -= 20;
    page.drawText("BEROEPS- EN BEDRIJFSAANSPRAKELIJKHEIDSVERZEKERING", {
      x: leftMargin, y, size: 10, font: helveticaBold, color: darkRed,
    });
    y -= 15;
    page.drawText("Dit certificaat maakt onderdeel uit van de polis van ZP Zaken b.v. onder polisnummer HPI.1006446", {
      x: leftMargin, y, size: 7, font: helvetica, color: gray,
    });

    y -= 30;

    // Separator
    page.drawLine({ start: { x: leftMargin, y }, end: { x: width - 60, y }, thickness: 0.5, color: lightGray });
    y -= 20;

    // Helper function to draw a field row
    const drawField = (label: string, value: string, fontSize = 9) => {
      page.drawText(label, { x: labelX, y, size: fontSize, font: helveticaBold, color: gray });
      // Handle multi-line values
      const lines = value.split("\n");
      lines.forEach((line: string, i: number) => {
        page.drawText(line, { x: valueX, y: y - i * 14, size: fontSize, font: helvetica, color: black });
      });
      y -= Math.max(20, lines.length * 14 + 6);
    };

    // Format date
    const formatDate = (dateStr: string) => {
      const d = new Date(dateStr);
      const months = ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"];
      const days = ["zondag", "maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag"];
      return `${days[d.getDay()]} ${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear()}`;
    };

    drawField("Certificaathouder:", policy.certificate_holder);
    drawField("Verzekeringsnemer:", policy.insured_name);
    drawField("Certificaatnummer:", policy.certificate_number);
    drawField("Ingangsdatum:", formatDate(policy.start_date));
    drawField("Hoedanigheid:", policy.profession);

    y -= 5;

    // Verzekerde bedragen
    page.drawText("Verzekerde bedragen:", { x: labelX, y, size: 9, font: helveticaBold, color: gray });
    
    page.drawText("Beroepsaansprakelijkheid", { x: valueX, y, size: 9, font: helveticaBold, color: darkRed });
    y -= 14;
    page.drawText(`${policy.bav_per_event}, - per aanspraak`, { x: valueX, y, size: 9, font: helvetica, color: black });
    y -= 14;
    page.drawText(`${policy.bav_per_year}, - per verzekeringsjaar`, { x: valueX, y, size: 9, font: helvetica, color: black });
    y -= 20;

    page.drawText("Bedrijfsaansprakelijkheid", { x: valueX, y, size: 9, font: helveticaBold, color: darkRed });
    y -= 14;
    page.drawText(`${policy.avb_per_event}, - per aanspraak`, { x: valueX, y, size: 9, font: helvetica, color: black });
    y -= 14;
    page.drawText(`${policy.avb_per_year}, - per verzekeringsjaar`, { x: valueX, y, size: 9, font: helvetica, color: black });
    y -= 25;

    const note = 'Waar op het polis blad wordt vermeld "per jaar voor alle leden tezamen" wordt';
    const note2 = 'gerefereerd aan het verzekerd bedrag per jaar.';
    page.drawText(note, { x: valueX, y, size: 8, font: helvetica, color: gray });
    y -= 12;
    page.drawText(note2, { x: valueX, y, size: 8, font: helvetica, color: gray });
    y -= 25;

    drawField("Eigen risico:", policy.own_risk);

    y -= 5;

    // Polisvoorwaarden
    page.drawText("Polisvoorwaarden:", { x: labelX, y, size: 9, font: helveticaBold, color: gray });
    page.drawText("Informatie en Communicatie Technologie", { x: valueX, y, size: 9, font: helvetica, color: black });
    y -= 14;
    page.drawText("• Voorwaarden beroepsaansprakelijkheid", { x: valueX, y, size: 8, font: helvetica, color: darkRed });
    y -= 12;
    page.drawText("• Voorwaarden bedrijfsaansprakelijkheid (kantoorrisico)", { x: valueX, y, size: 8, font: helvetica, color: darkRed });
    y -= 12;
    page.drawText("• Verzekeringskaart", { x: valueX, y, size: 8, font: helvetica, color: darkRed });
    y -= 25;

    drawField("Dekkingsgebied:", policy.coverage_area);
    drawField("Contractduur:", policy.contract_duration);

    y -= 5;

    // Tussenpersoon
    page.drawText("Tussenpersoon:", { x: labelX, y, size: 9, font: helveticaBold, color: gray });
    page.drawText("ZP Zaken.", { x: valueX, y, size: 9, font: helvetica, color: black });
    y -= 14;
    page.drawText("AFM vergunningnummer: 12050636", { x: valueX, y, size: 9, font: helvetica, color: black });
    y -= 25;

    drawField("Afgiftedatum:", formatDate(policy.issued_date));
    drawField("Voor gezien ZP Zaken:", policy.issued_by);

    // Footer
    const footerY = 40;
    page.drawLine({ start: { x: leftMargin, y: footerY + 10 }, end: { x: width - 60, y: footerY + 10 }, thickness: 0.5, color: lightGray });
    page.drawText(
      "De verzekeringsmaterialen van ZP Zaken zijn alleen toegankelijk voor klanten van ZP Zaken en treedt hierbij op geen enkele wijze op als financiële dienstverlener of bemiddelaar zoals gesteld onder de Wft.",
      { x: leftMargin, y: footerY, size: 5.5, font: helvetica, color: gray }
    );
    page.drawText(
      "De verstrekte gegevens zullen strikt vertrouwelijk worden behandeld. ZP Zaken is ingeschreven in het register Wft bij de AFM onder vergunningnummer: 12050363.",
      { x: leftMargin, y: footerY - 8, size: 5.5, font: helvetica, color: gray }
    );

    // Save PDF
    const pdfBytes = await pdfDoc.save();
    const fileName = `${policy.certificate_number}.pdf`;

    // Upload to storage
    const { error: uploadError } = await adminClient.storage
      .from("certificates")
      .upload(fileName, pdfBytes, {
        contentType: "application/pdf",
        upsert: true,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      return new Response(JSON.stringify({ error: "Failed to upload PDF", details: uploadError.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get signed URL (valid for 1 hour)
    const { data: signedUrlData } = await adminClient.storage
      .from("certificates")
      .createSignedUrl(fileName, 3600);

    // Update policy with PDF path
    await adminClient
      .from("policies")
      .update({ pdf_url: fileName })
      .eq("id", policy.id);

    return new Response(
      JSON.stringify({
        success: true,
        policy: {
          id: policy.id,
          certificate_number: policy.certificate_number,
          pdf_url: signedUrlData?.signedUrl || null,
          pdf_path: fileName,
        },
      }),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
