// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-published-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@2.108.2";
import { z } from "npm:zod@^3.25.76";
var list_published_articles_default = defineTool({
  name: "list_published_articles",
  title: "List published Kennisbank articles",
  description: "List published articles from the ZP Zaken Kennisbank (title, slug, category, published_at, excerpt). Read-only, no authentication required.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of articles to return."),
    category: z.string().optional().describe("Optional category slug/name to filter by (matches articles.category).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured" }], isError: true };
    }
    const supabase = createClient(url, key, { auth: { persistSession: false } });
    let q = supabase.from("articles").select("title, slug, excerpt, category, published_at").eq("is_published", true).order("published_at", { ascending: false }).limit(limit);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.108.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_article_default = defineTool2({
  name: "get_article",
  title: "Get Kennisbank article by slug",
  description: "Fetch a single published Kennisbank article (including full Markdown content) by its slug. Read-only.",
  inputSchema: {
    slug: z2.string().min(1).describe("The article slug, e.g. 'bav-voor-it-zzp'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !key) {
      return { content: [{ type: "text", text: "Backend not configured" }], isError: true };
    }
    const supabase = createClient2(url, key, { auth: { persistSession: false } });
    const { data, error } = await supabase.from("articles").select("title, slug, excerpt, content, category, seo_title, seo_description, published_at").eq("is_published", true).eq("slug", slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No published article found with slug '${slug}'.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  {
    key: "bav",
    name: "Beroepsaansprakelijkheidsverzekering (BAV)",
    url: "https://zzpproject.lovable.app/verzekeringen",
    description: "Beroepsaansprakelijkheid voor zzp'ers, met focus op IT, consultancy, HR, marketing en coaches."
  },
  {
    key: "avb",
    name: "Bedrijfsaansprakelijkheidsverzekering (AVB)",
    url: "https://zzpproject.lovable.app/verzekeringen",
    description: "AVB voor zzp'ers, veelal gecombineerd met BAV."
  },
  {
    key: "aov",
    name: "Arbeidsongeschiktheidsverzekering (AOV)",
    url: "https://zzpproject.lovable.app/aov",
    description: "Inkomensbescherming bij arbeidsongeschiktheid."
  },
  {
    key: "wet-dba",
    name: "Wet DBA screening",
    url: "https://zzpproject.lovable.app/dba-verificatie",
    description: "DBA-check en certificering voor opdrachten van zzp'ers."
  },
  {
    key: "credit-control",
    name: "Credit control & factoring",
    url: "https://zzpproject.lovable.app/credit-control",
    description: "Uitbetaling binnen 24 uur en dekking van insolventierisico."
  }
];
var list_services_default = defineTool3({
  name: "list_services",
  title: "List ZP Zaken services",
  description: "Return the public list of ZP Zaken services (name, short description, URL). No authentication required.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "zpzaken-mcp",
  title: "ZP Zaken",
  version: "0.1.0",
  instructions: "Public tools for the ZP Zaken website. Use `list_services` to see what ZP Zaken offers (BAV, AVB, AOV, Wet DBA, credit control). Use `list_published_articles` and `get_article` to browse the Kennisbank knowledge base of published articles for Dutch zzp'ers.",
  tools: [list_published_articles_default, get_article_default, list_services_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
